version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    networks:
      - db-net
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./dindin-app
    networks:
      - db-net
    links:
      - 'mysqldb:mysql'
    working_dir: /usr/src/dindin-api
    container_name: dindin-api
    restart: always
    env_file: ./.env
    volumes:
      - ./dindin-app:/usr/src/dindin-api
      - node_modules:/usr/src/dindin-api/node_modules
    ports:
      - $NODE_LOCAL_PORT:$NODE_PUBLIC_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    command: /bin/bash -c "/usr/wait-for-it.sh --timeout=0 mysqldb:3306 && npm install && npm run $NPM_DOCKER_CMD"

volumes:
  db:
  node_modules:

networks:
    db-net:
