name: Flutter build

on:
  push:
    branches: [master]
    paths:
      - "Codigo/dindin-mobile/**"
  pull_request:
    branches: [master]
    paths:
      - "Codigo/dindin-mobile/**"

jobs:
  ios-build:
    name: Build for iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.x"
          channel: "stable" # or: 'beta' or 'master'
      - name: install, test and build
        working-directory: ./Codigo/dindin-mobile/dindin
        run: |
          flutter pub get
          flutter build ios --release --no-codesign

  android-build:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.x"
          channel: "stable"
      - name: install, test and build
        working-directory: ./Codigo/dindin-mobile/dindin
        run: |
          flutter pub get
          flutter build apk
          flutter build appbundle

  web-build:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.x"
          channel: "stable"
      - name: install, test and build
        working-directory: ./Codigo/dindin-mobile/dindin
        run: |
          flutter pub get
          flutter build web
